FROM spikeinterface/kilosort2_5-compiled-base:latest

ARG DEBIAN_FRONTEND=noninteractive

# install libvips
RUN apt-get update \
    && apt-get install -y libvips libvips-dev libvips-tools libtiff5-dev
# correct mapping to make libvips work
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7
RUN rm /opt/matlabruntime/R2022b/bin/glnxa64/libtiff.so.5
RUN ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4 /opt/matlabruntime/R2022b/bin/glnxa64/libtiff.so.5


# install default fonts
RUN apt-get install -y msttcorefonts fonts-freefont-ttf

RUN pip install -U --no-cache-dir --ignore-installed jupyter

# needed for correct functioning of sortingview
RUN pip install -U --no-cache-dir --ignore-installed \
    pyvips==2.2.1 \
    pynwb==2.5.0 \
    spikeinterface[full,widgets]==0.100.0
