#!/usr/bin/env bash
set -e

# install spikeinterface extras
pip install --no-cache-dir --ignore-installed spikeinterface[full,widgets]==0.98.0

# install aind-data-schema from source
git clone https://github.com/AllenNeuralDynamics/aind-data-schema.git
cd aind-data-schema
git checkout f5d3f3ee31bf59077b16fd17211104708055e3f6
pip install --no-cache-dir --ignore-installed .
cd ..


# pin setuptools to remove warnings
pip install --no-cache-dir --ignore-installed setuptools==67.2.0
