#!/usr/bin/env bash
set -e

# install spikeinterface
pip install --no-cache-dir --ignore-installed spikeinterface[full,widgets]==0.98.1


# pin setuptools to remove warnings
pip install --no-cache-dir --ignore-installed setuptools==67.2.0
